algoritmo "lersomar"
// Função :Solicitar um numero e somar até dar zero
// Autor : Cláudio Endo
// Data : 16/09/2020
// Seção de Declarações 
var
 soma, numeros: inteiro
inicio
// Seção de comandos
 numeros <- 1
 soma <- 0
 enquanto numeros <> 0 faca
 escreval("Digite um numero:")
 leia(numeros)

 soma <- soma + numeros
 fimenquanto
 escreval("O resultado da soma dos numeros é: ", soma)
fimalgoritmo
