algoritmo "escolaribeirao"
// Função :Informar qual a melhor escola de Ribeirão
// Autor :Cláudio Endo
// Data : 16/09/2020
var
nome:caractere
inicio
// Seção de comandos
  escreval("Qual a melhor escola de Ribeirão Pires")

repita
  escreval("Digite qual a melhor escola de Ribeirão Pires:")
  leia(nome)
  
escreval("Voce digitou a escola errada:")

ate(nome="ETEC MCM")

 escreval("Voce digitou a escola certa")
 fimalgoritmo
